scrape_configs:
  - job_name: 'nginx'
    scrape_interval: 10s  
    static_configs:
      - targets: ['nginx_exporter:9113']
  - job_name: 'redis'
    scrape_interval: 10s  
    static_configs:
      - targets: ['redis_exporter:9121']
  - job_name: 'postgres'
    scrape_interval: 10s  
    static_configs:
      - targets: ['postgres_exporter:9187']